# Generated by Django 6.0.7 on 2026-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('operation_manager', 'Operation Manager'), ('psychologist', 'Psychologist'), ('ccd', 'CCD Staff'), ('admin', 'Admin')], default='psychologist', max_length=20),
        ),
    ]
