# Generated by Django 6.0.7 on 2026-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('Initial Consultation', 'Initial Consultation'), ('Follow-up', 'Follow-up')], default='Initial Consultation', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.CharField(default='50 mins', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mode',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=20),
        ),
    ]
