# Generated by Django 6.0.7 on 2026-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
