# Generated by Django 5.2 on 2026-07-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_problems', models.TextField(blank=True, null=True)),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('psychiatric_history', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('personal_history', models.TextField(blank=True, null=True)),
                ('social_history', models.TextField(blank=True, null=True)),
                ('mental_status_examination', models.JSONField(blank=True, default=dict)),
                ('diagnosis', models.JSONField(blank=True, default=dict)),
                ('treatment_plan', models.JSONField(blank=True, default=dict)),
                ('risk_assessment', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='clients.client')),
                ('psychologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_histories', to='authentication.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('duration', models.CharField(default='50 mins', max_length=50)),
                ('notes', models.TextField()),
                ('homework', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='clients.client')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='authentication.psychologist')),
            ],
        ),
    ]
