# Generated by Django 6.0.7 on 2026-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='clinical_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='educational_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='occupational_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='relationship_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='substance_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='therapist_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='treatment_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='clinical_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='progress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Severe', 'Severe')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='therapist_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='treatment_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
