# Generated by Django 6.0.7 on 2026-07-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
        ('case_history', '0002_casehistory_clinical_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionnote',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_notes', to='authentication.psychologist'),
        ),
    ]
